name: Build JOSS paper

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile JOSS paper to PDF
        uses: openjournals/inara@v1.1.5
        with:
          path: './'
          paper: 'JOSS_paper.md'

      - name: Upload compiled PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
